name: Release Shared Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [1,2,3,4,5,6,7,8,9,10,
                11,12,13,14,15,16,17,18,19,20,
                21,22,23,24,25,26,27,28,29,30,
                31,32,33,34,35,36]  # Indices for 37 parallel jobs
    continue-on-error: true  # Allow individual build jobs to fail
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Download Latest Release Assets
        run: |
          mkdir -p output
          echo "Downloading latest release assets..."
          urls=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest \
            | grep "browser_download_url.*\.grib2" \
            | cut -d '"' -f 4)
          for url in $urls; do
            echo "Downloading $url"
            curl -L -o output/$(basename $url) $url
          done
          # file name: gfs.0p25.${date_str}${hour}.f006.grib2"
          # remove files that are 1yr old
          OUTPUT_DIR="output"

          # Get the current date minus one year in YYYYMMDD format
          ONE_YEAR_AGO=$(date -u -d "now -1 year" +"%Y%m%d")

          # Loop through the files matching the pattern
          for file in "${OUTPUT_DIR}/gfs.0p25."*.f006.grib2; do
              # Extract the date from the filename
              # Filename format: gfs.0p25.YYYYMMDDHH.f006.grib2
              basename=$(basename "$file")
              date_part=$(echo "$basename" | awk -F'.' '{print $3}')
              file_date=${date_part:0:8}  # Extract YYYYMMDD

              # Compare the file date with the date from one year ago
              if [[ "$file_date" < "$ONE_YEAR_AGO" ]]; then
                  echo "Deleting file: $file (Date: $file_date)"
                  rm "$file" || true
              fi
          done

      - name: Calculate Start Date
        id: calc_date
        run: |
          base_date=$(date -u +"%Y%m%d")
          index=${{ matrix.index }}
          default_num_days=10
          total_days=365
          start_offset=$(( index * default_num_days ))
          start_date=$(date -u -d "$base_date -$start_offset days" +"%Y%m%d")
          remaining_days=$(( total_days - index * default_num_days ))
          if [ $remaining_days -ge $default_num_days ]; then
            num_days=$default_num_days
          elif [ $remaining_days -gt 0 ]; then
            num_days=$remaining_days
          else
            echo "No days left to process."
            exit 0
          fi
          echo "start_date=${start_date}" >> $GITHUB_ENV
          echo "num_days=${num_days}" >> $GITHUB_ENV

      - name: Run Historical Data Download
        run: |
          chmod +x ./ncar.sh
          ./ncar.sh $start_date $num_days

      - name: Upload Artifacts
        if: always() || cancelled() # Always upload artifacts, even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: "snow_data_${{ env.start_date }}"
          path: output/*.grib2

  release:
    runs-on: ubuntu-latest
    needs: build-linux
    if: always()  # Run even if previous jobs failed
    steps:
      - uses: actions/checkout@v3

      - name: Tag the commit
        run: |
          base_date=$(date -u +"%Y%m%d")
          git tag -a "${base_date}" -m "Snow data for ${base_date}"

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: all_output

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: all_output/**/*.grib2
          prerelease: false