name: Release Shared Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [0,1,2,3,4,5,6,7,8,9,10,
                11,12,13,14,15,16,17,18,19,20,
                21,22,23,24,25,26,27,28,29,30,
                31,32,33,34,35,36]  # Indices for 37 parallel jobs
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Download Latest Release Assets
        run: |
          mkdir -p output
          echo "Downloading latest release assets..."
          urls=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest \
            | grep "browser_download_url.*\.grib2" \
            | cut -d '"' -f 4)
          for url in $urls; do
            echo "Downloading $url"
            curl -L -o output/$(basename $url) $url
          done

      - name: Calculate Start Date
        id: calc_date
        run: |
          base_date="20221001"
          index=${{ matrix.index }}
          default_num_days=10
          total_days=365
          start_offset=$(( index * default_num_days ))
          start_date=$(date -u -d "$base_date +$start_offset days" +"%Y%m%d")
          remaining_days=$(( total_days - index * default_num_days ))
          if [ $remaining_days -ge $default_num_days ]; then
            num_days=$default_num_days
          elif [ $remaining_days -gt 0 ]; then
            num_days=$remaining_days
          else
            echo "No days left to process."
            exit 0
          fi
          echo "start_date=${start_date}" >> $GITHUB_ENV
          echo "num_days=${num_days}" >> $GITHUB_ENV

      - name: Run Historical Data Download
        run: |
          chmod +x ./ncar.sh
          ./ncar.sh $start_date $num_days

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "snow_data_${{ env.start_date }}"
          path: output/snow_*.grib2

  release:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: all_output

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: all_output/**/*.grib2
          prerelease: false