name: Release Shared Workflow

on:
    # every 24h
    schedule:
      - cron:  '0 0 * * *'
    # mauall trigger
    workflow_dispatch:
    

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
        CDSAPI_URL: "https://cds.climate.copernicus.eu/api/v2"

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Setup 
      run: |
        python3.12 -m pip install -r requirements.txt

    - name: Run Downloader
      run: |
        echo "url: $CDSAPI_URL" > $(pwd)/cdsapirc
        echo "key: ${{ secrets.CDSAPI_KEY }}""  >> $(pwd)/cdsapirc
        cat $(pwd)/cdsapirc
        CDSAPI_RC=$(pwd)/cdsapirc python3.12 download.py
        ls -la
        mv *.grib europe.grib

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: autoortho_osx_*.bin
        prerelease: false


